package config

const (
	ToolName               = "skiff"
	CatalogFile            = "catalog.yaml"
	TerragruntTemplateFile = "terragrunt.default.tmpl"
	SkiffConfigFile        = ".skiff"
	ScopeRegional          = "regional"
	ScopeGlobal            = "global"
	ServiceKey             = "service"
	GroupKey               = "group"
	ContextKey             = "config"
	RegionKey              = "region"
	TypeKey                = "type"
	TagsKey                = "tags"
	ScopeKey               = "scope"
	VersionKey             = "version"
	DependencyKey          = "dependencies"
	NameKey                = "name"
	SourceKey              = "source"
	BodyKey                = "body"
	InputsKey              = "inputs"
	TerraformKey           = "terraform"
	TerraformAttributesKey = "terraform_attributes"
	ServiceConfigKey       = "service_config"
	VarKey                 = "var"
	ConfigPathKey          = "config_path"
	OutputsKey             = "outputs"
)
